apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: myapp
spec:
  vars:
    external:
      - name: image_tag
        default: ':latest'
  environments:
    stage:
      defaultNamespace: stage
      server: https://130.193.51.34:6443
    prod:
      defaultNamespace: default
      server: https://130.193.51.34:6443
#vars: {}
