apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: myapp
spec:
  environments:
    stage:
      defaultNamespace: stage
      server: https://51.250.4.128:6443
    prod:
      defaultNamespace: default
      server: https://51.250.4.128:6443

  vars: {}
